version: '3'
services:
  redis-1:
    container_name: "redis-1"
    image: redis
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command:  redis-server /etc/redis/redis.conf --port 7000
    networks:
      - redis-net
  redisinsight:
    container_name: "redisinsight"
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis-1:7000
    networks:
      - redis-net



networks:
  redis-net:

#redis-cli --cluster create redis-1:7000 redis-2:7001 redis-3:7002 redis-4:7003 redis-5:7004 redis-6:7005 --cluster-replicas 1
